### ISSUE TITLE
Module installation via pip fails

### ISSUE THREAD

**Issue by SanabriaRusso** [jd-boyd/sexpdata#45]
Hello!

During the installation via `pip` I get the following error:

```text
python -m pip install sexpdata
Collecting sexpdata
  Using cached sexpdata-1.0.1.tar.gz (8.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [75 lines of output]
      /private/var/folders/yk/f369l6yx6890jq3z62mlkn1w0000gn/T/pip-build-env-92yauvn1/overlay/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py:75: _MissingDynamic: `license` defined outside of `pyproject.toml` is ignored.
      !!

              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:

              `license = 'BSD License'`

              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `license` is listed as `dynamic`.

              https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

              To prevent this problem, you can list `license` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************

      !!
        _handle_missing_dynamic(dist, project_table)
      /private/var/folders/yk/f369l6yx6890jq3z62mlkn1w0000gn/T/pip-build-env-92yauvn1/overlay/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py:75: _MissingDynamic: `keywords` defined outside of `pyproject.toml` is ignored.
      !!

              ********************************************************************************
              The following seems to be defined outside of `pyproject.toml`:

              `keywords = ['s-expression', 'lisp', 'parser']`

              According to the spec (see the link below), however, setuptools CANNOT
              consider this value unless `keywords` is listed as `dynamic`.

              https://packaging.python.org/en/latest/specifications/declaring-project-metadata/

              To prevent this problem, you can list `keywords` under `dynamic` or alternatively
              remove the `[project]` table from your file and rely entirely on other means of
              configuration.
              ********************************************************************************

      !!
        _handle_missing_dynamic(dist, project_table)
      Traceback (most recent call last):
        File "/Users/sanabriarusso/Desktop/eraseme/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/sanabriarusso/Desktop/eraseme/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/sanabriarusso/Desktop/eraseme/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yk/f369l6yx6890jq3z62mlkn1w0000gn/T/pip-build-env-92yauvn1/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yk/f369l6yx6890jq3z62mlkn1w0000gn/T/pip-build-env-92yauvn1/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/yk/f369l6yx6890jq3z62mlkn1w0000gn/T/pip-build-env-92yauvn1/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
        File "/private/var/folders/yk/f369l6yx6890jq3z62mlkn1w0000gn/T/pip-build-env-92yauvn1/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yk/f369l6yx6890jq3z62mlkn1w0000gn/T/pip-build-env-92yauvn1/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/private/var/folders/yk/f369l6yx6890jq3z62mlkn1w0000gn/T/pip-build-env-92yauvn1/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 627, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/private/var/folders/yk/f369l6yx6890jq3z62mlkn1w0000gn/T/pip-build-env-92yauvn1/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 67, in apply_configuration
          return _apply(dist, config, filepath)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/yk/f369l6yx6890jq3z62mlkn1w0000gn/T/pip-build-env-92yauvn1/overlay/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 56, in apply
          _apply_project_table(dist, config, root_dir)
        File "/private/var/folders/yk/f369l6yx6890jq3z62mlkn1w0000gn/T/pip-build-env-92yauvn1/overlay/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 82, in _apply_project_table
          corresp(dist, value, root_dir)
        File "/private/var/folders/yk/f369l6yx6890jq3z62mlkn1w0000gn/T/pip-build-env-92yauvn1/overlay/lib/python3.11/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 183, in _license
          _set_config(dist, "license", val["text"])
                                       ~~~^^^^^^^^
      KeyError: 'text'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Accordingly, in order to resolve this issue changes to the way project configuration is carried out. This may be done by listing `license` under `dynamic`. The same issue is raised by `keywords`, which in order to be considered should be inside `pyproject.toml` and under `dynamic`.

**Comment by bukatea** [comment]
For me downgrading to 1.0.0 solved the issue temporarily.

**Comment by trevormalloy** [comment]
downgrading to 1.0.0 worked for us as well.

**Comment by kendra-human** [comment]
I don't use this package, found this thread from Google.

I'm seeing this same error with other dependencies I have when building. Does anyone know what the underlying issue is? Is it a breaking change in setuptools?

**Comment by jd-boyd** [comment]
I think this is now fixed. Feel free to re-open if I'm wrong.

**Comment by agroszer** [comment]
Please make a release

**Comment by efokken-abb** [comment]
Please only make a release after also merging #47 and testing that the build works.
Unfortunately I cannot test it, because I don't have the correct pip/setuptools/not sure what at hand.

**Comment by tkra90** [comment]
I managed to fix this issue, by adding `license = {text = "MIT License"}` to my pyproject.toml / [project]

> setuptools.__version__
> '58.1.0'

**Comment by jd-boyd** [comment]
> Please only make a release after also merging #47 and testing that the build works. Unfortunately I cannot test it, because I don't have the correct pip/setuptools/not sure what at hand.

Version 1.0.2 has now been released.

**Comment by efokken-abb** [comment]
it works in my projects!
